const B=(en,no)=>({en,no});
const H=(id,en,no,consequences,measures)=>({id,label:B(en,no),consequences:consequences.map(([e,n])=>B(e,n)),measures:measures.map(m=>({id:m[0],label:B(m[1],m[2]),sourceType:m[3]||'recommended',source:B(m[4]||'',m[5]||'')}))});
const Q=(id,en,no,critical=false)=>({id,text:B(en,no),critical});

export const activityLibrary=[
  {id:'boom_lift',category:'height',name:B('Work from boom lift','Arbeid fra bomlift'),description:B('Work performed from a mobile elevating work platform/boom lift.','Arbeid utført fra mobil arbeidsplattform/bomlift.'),
    hazards:[
      H('fall','Fall from platform','Fall fra arbeidsplattform',[["Serious injury or fatality","Alvorlig personskade eller dødsfall"]],[['harness','Use fall protection when required by the machine instructions and risk assessment','Bruk fallsikring når maskinens instruksjoner og risikovurderingen krever det','manufacturer','Manufacturer instructions','Produsentinstruksjon'],['tools','Secure tools and loose equipment','Sikre verktøy og løst utstyr']]),
      H('crush','Crushing / entrapment against structure','Klemming mot konstruksjon',[["Crushing injuries","Klemskader"]],[['spotter','Use spotter where visibility or clearance is limited','Bruk signalmann der sikt eller klaring er begrenset'],['clearance','Plan movement and maintain safe clearance','Planlegg bevegelse og hold sikker klaring']]),
      H('tip','Tip-over / unstable ground','Velt / ustabilt underlag',[["Serious injury, equipment and property damage","Alvorlig personskade, skade på utstyr og eiendom"]],[['ground','Check ground conditions and load-bearing capacity','Kontroller underlag og bæreevne'],['limits','Follow machine limits for slope, load and stabilisers','Følg maskinens grenser for helning, last og støtteben','manufacturer','Manufacturer instructions','Produsentinstruksjon']]),
      H('weather','Wind / adverse weather','Vind / ugunstige værforhold',[["Loss of control or tip-over","Tap av kontroll eller velt"]],[['wind','Check weather and manufacturer wind limits','Kontroller vær og produsentens vindgrenser','manufacturer','Manufacturer instructions','Produsentinstruksjon']]),
      H('electric','Electrical installations','Elektriske installasjoner',[["Electric shock, burns or fatality","Strømgjennomgang, brannskade eller dødsfall"]],[['distance','Identify electrical hazards and maintain required safe distance','Identifiser elektriske farer og hold påkrevd sikker avstand','requirement','Applicable electrical safety requirements','Gjeldende elsikkerhetskrav']])
    ],
    questions:[Q('trained','Are operators trained for the actual lift/equipment?','Har operatørene opplæring for aktuell lift/utstyr?',true),Q('inspection','Has the required pre-use inspection been completed?','Er påkrevd kontroll før bruk gjennomført?',true),Q('rescue','Is emergency lowering/rescue understood and available?','Er nødsenking/redning kjent og tilgjengelig?',true)]},

  {id:'roof',category:'height',name:B('Roof work / work at height','Takarbeid / arbeid i høyden'),description:B('Work with exposure to falls from edges, openings or fragile surfaces.','Arbeid med eksponering for fall fra kanter, åpninger eller svake flater.'),
    hazards:[
      H('edge','Fall from edge/opening','Fall fra kant/åpning',[["Serious injury or fatality","Alvorlig personskade eller dødsfall"]],[['collective','Prioritise collective fall prevention where practicable','Prioriter kollektiv fallsikring der det er praktisk mulig','requirement','Work-at-height requirements / company procedure','Krav til arbeid i høyden / virksomhetens prosedyre'],['personal','Use suitable personal fall protection where required','Bruk egnet personlig fallsikring der det kreves']]),
      H('fragile','Fragile roof/surface','Svakt tak/underlag',[["Fall through surface","Fall gjennom underlag"]],[['verify','Verify construction, strength and fragile areas before work','Verifiser konstruksjon, bæreevne og svake områder før arbeid'],['walkway','Use suitable walkways/platforms where needed','Bruk egnede gangbaner/plattformer ved behov']]),
      H('objects','Falling objects','Fallende gjenstander',[["Injury to persons below","Skade på personer under"]],[['zone','Establish exclusion zone below','Etabler sperresone under'],['secure','Secure tools/materials','Sikre verktøy/materialer']])
    ],questions:[Q('access','Is safe access/egress established?','Er sikker adkomst/rømningsvei etablert?',true),Q('rescue','Is rescue after a fall planned where relevant?','Er redning etter fall planlagt der det er relevant?',true)]},

  {id:'ladder',category:'height',name:B('Ladder work','Arbeid fra stige'),description:B('Short-duration access or work involving ladders.','Kortvarig adkomst eller arbeid med stige.'),hazards:[
    H('fall','Fall from ladder','Fall fra stige',[["Injury from fall","Personskade ved fall"]],[['suitability','Verify ladder is suitable for the task and duration','Verifiser at stigen er egnet for oppgaven og varigheten'],['secure','Place and secure ladder on stable surface','Plasser og sikre stigen på stabilt underlag']]),
    H('drop','Dropped tools/materials','Fallende verktøy/materialer',[["Injury to persons below","Skade på personer under"]],[['zone','Keep area below controlled','Hold området under kontrollert'],['carry','Maintain safe handling / use tool bags','Sørg for sikker håndtering / bruk verktøybag']])
  ],questions:[Q('alternative','Has a safer work platform been considered?','Er en sikrere arbeidsplattform vurdert?',true),Q('condition','Has the ladder condition been checked?','Er stigens tilstand kontrollert?',true)]},

  {id:'scaffold',category:'height',name:B('Scaffold work','Arbeid på stillas'),description:B('Work on or around fixed/mobile scaffold.','Arbeid på eller rundt fast/rullestillas.'),hazards:[
    H('fall','Fall from scaffold','Fall fra stillas',[["Serious injury","Alvorlig personskade"]],[['guard','Verify guardrails, toe boards and access','Kontroller rekkverk, fotlist og adkomst'],['inspection','Ensure scaffold is inspected/released for use','Sørg for at stillaset er kontrollert/frigitt for bruk']]),
    H('collapse','Scaffold instability/collapse','Ustabilitet/kollaps av stillas',[["Multiple serious injuries / damage","Flere alvorlige personskader / skade"]],[['foundation','Check foundation, anchoring and loading','Kontroller fundament, forankring og belastning']])
  ],questions:[Q('tag','Is the scaffold inspected and released for use?','Er stillaset kontrollert og frigitt for bruk?',true),Q('changes','Is it confirmed that any scaffold modification will only be made by competent personnel?','Er det bekreftet at eventuelle endringer på stillaset bare utføres av kompetent personell?',true)]},

  {id:'lifting',category:'lifting',name:B('Lifting operation','Løfteoperasjon'),description:B('Lifting with crane, hoist, forklift or other lifting equipment.','Løft med kran, talje, truck eller annet løfteutstyr.'),hazards:[
    H('suspended','Suspended load / falling load','Hengende last / fallende last',[["Crushing, serious injury or fatality","Klemskade, alvorlig personskade eller dødsfall"]],[['zone','Establish and maintain exclusion zone','Etabler og oppretthold sperresone'],['gear','Verify lifting gear capacity and condition','Verifiser kapasitet og tilstand på løfteredskap']]),
    H('swing','Swinging/uncontrolled load','Svingende/ukontrollert last',[["Impact or crushing injury","Slag- eller klemskade"]],[['plan','Plan lift path and control the load','Planlegg løftebane og kontroller lasten'],['comms','Establish clear communication/signals','Etabler tydelig kommunikasjon/signaler']])
  ],questions:[Q('plan','Is the lift planned and roles assigned?','Er løftet planlagt og roller fordelt?',true),Q('capacity','Are equipment and lifting accessories suitable for the load?','Er utstyr og løfteredskap egnet for lasten?',true),Q('zone','Can the exclusion zone be maintained?','Kan sperresonen opprettholdes?',true)]},

  {id:'hot_work',category:'fire',name:B('Hot work','Varme arbeider'),description:B('Work producing flame, sparks or heat.','Arbeid som produserer flamme, gnister eller varme.'),hazards:[
    H('fire','Fire / ignition','Brann / antennelse',[["Fire, burns, property damage","Brann, brannskader, materielle skader"]],[['remove','Remove/protect combustible materials in the risk area','Fjern/beskytt brennbart materiale i risikoområdet'],['openings','Seal/protect openings that can spread sparks or heat','Tett/beskytt åpninger som kan spre gnister eller varme'],['ext','Provide suitable extinguishing equipment','Ha egnet slokkeutstyr tilgjengelig']]),
    H('fumes','Fumes / smoke','Røyk / gasser',[["Respiratory exposure","Eksponering av luftveier"]],[['vent','Ensure suitable ventilation/extraction','Sørg for egnet ventilasjon/avsug']])
  ] ,questions:[Q('scope','Is it clarified which hot-work safety rules/insurance requirements apply?','Er det avklart hvilke sikkerhets-/forsikringskrav for varme arbeider som gjelder?',true),Q('checklist','Is the required hot-work checklist completed where applicable?','Er påkrevd sjekkliste for varme arbeider utfylt der den gjelder?',true),Q('alarm','If fire detection is affected, are approval and compensating measures arranged?','Hvis branndeteksjon påvirkes, er godkjenning og kompenserende tiltak etablert?',true)]},

  {id:'chemicals',category:'chemical',name:B('Chemical use','Arbeid med kjemikalier'),description:B('Handling or use of chemicals, cleaning agents, solvents or hazardous substances.','Håndtering eller bruk av kjemikalier, rengjøringsmidler, løsemidler eller farlige stoffer.'),hazards:[
    H('exposure','Skin/eye/inhalation exposure','Hud-/øye-/innåndingseksponering',[["Irritation, burns or poisoning","Irritasjon, etseskade eller forgiftning"]],[['sds','Review safety data and required controls','Gjennomgå sikkerhetsdata og nødvendige tiltak','requirement','Safety data sheet / product instructions','Sikkerhetsdatablad / produktinstruksjon'],['ppe','Select suitable PPE','Velg egnet personlig verneutstyr']]),
    H('mix','Incompatible substances / reaction','Uforenlige stoffer / reaksjon',[["Fire, toxic gas or violent reaction","Brann, giftig gass eller kraftig reaksjon"]],[['segregate','Prevent incompatible mixing and store correctly','Hindre uforenlig blanding og oppbevar korrekt']])
  ],questions:[Q('sds','Is current product/safety information available and understood?','Er oppdatert produkt-/sikkerhetsinformasjon tilgjengelig og forstått?',true),Q('spill','Are required spill and first-aid measures available?','Er nødvendige tiltak for søl og førstehjelp tilgjengelige?',true)]},

  {id:'electrical',category:'electrical',name:B('Electrical work / work near electrical installations','Elektrisk arbeid / arbeid nær elektriske installasjoner'),description:B('Tasks involving electrical equipment or proximity to electrical hazards.','Oppgaver med elektrisk utstyr eller nærhet til elektriske farer.'),hazards:[
    H('shock','Electric shock / arc','Strømgjennomgang / lysbue',[["Burns, serious injury or fatality","Brannskade, alvorlig personskade eller dødsfall"]],[['isolate','Isolate/de-energise where required and verify safe state','Frakoble spenningskilder der det kreves og verifiser sikker tilstand','requirement','Applicable electrical safety requirements / company procedure','Gjeldende elsikkerhetskrav / virksomhetens prosedyre'],['distance','Maintain required clearances and barriers','Oppretthold nødvendige avstander og barrierer']])
  ],questions:[Q('competence','Are competence/authorisation requirements fulfilled?','Er krav til kompetanse/autorisasjon oppfylt?',true),Q('isolation','Where isolation/lockout is required, is it established?','Der frakobling/låsing kreves, er dette etablert?',true),Q('verify','Can the safe electrical state be verified before work starts?','Kan sikker elektrisk tilstand verifiseres før arbeidet starter?',true)]},

  {id:'traffic',category:'traffic',name:B('Work near traffic','Arbeid nær trafikk'),description:B('Work exposed to vehicles, mobile plant or public traffic.','Arbeid eksponert for kjøretøy, mobile maskiner eller offentlig trafikk.'),hazards:[
    H('hit','Vehicle/person collision','Påkjørsel/kollisjon',[["Serious injury or fatality","Alvorlig personskade eller dødsfall"]],[['separate','Separate people and vehicles where practicable','Skill personer og kjøretøy der det er praktisk mulig'],['barriers','Use signs/barriers/traffic control as required','Bruk skilt/sperringer/trafikkdirigering etter behov']]),
    H('reversing','Reversing / blind zones','Rygging / blindsoner',[["Crushing injury","Klemskade"]],[['spotter','Use spotter or other controls for blind movements','Bruk signalmann eller andre tiltak ved blind bevegelse']])
  ],questions:[Q('plan','Is traffic management established for the work?','Er trafikkavvikling etablert for arbeidet?',true),Q('public','Is the work zone protected from unauthorised entry?','Er arbeidsområdet sikret mot uvedkommende?',true),Q('visibility','Are visibility and lighting adequate?','Er sikt og belysning tilstrekkelig?',true)]},

  {id:'confined',category:'confined',name:B('Confined space','Arbeid i lukket rom'),description:B('Entry/work in confined or poorly ventilated spaces.','Inngang/arbeid i lukkede eller dårlig ventilerte rom.'),hazards:[
    H('atmosphere','Hazardous atmosphere / oxygen deficiency','Farlig atmosfære / oksygenmangel',[["Loss of consciousness, poisoning or fatality","Bevisstløshet, forgiftning eller dødsfall"]],[['test','Assess/test atmosphere as required','Vurder/test atmosfæren etter behov'],['vent','Provide ventilation where required','Sørg for ventilasjon der det kreves']]),
    H('rescue','Difficult rescue/access','Vanskelig redning/adkomst',[["Delayed rescue / worsened consequences","Forsinket redning / forverrede konsekvenser"]],[['rescueplan','Establish rescue plan and resources before entry','Etabler redningsplan og ressurser før inngang']])
  ],questions:[Q('permit','Where entry permit/authorisation is required, is it in place?','Der inngangstillatelse/autorisasjon kreves, er den på plass?',true),Q('rescue','Is a practicable rescue plan in place?','Er en gjennomførbar redningsplan på plass?',true),Q('watch','Where standby/safety watch is required, is it established?','Der sikkerhetsvakt kreves, er den etablert?',true)]},

  {id:'excavation',category:'ground',name:B('Excavation / trench work','Gravearbeid / grøft'),description:B('Excavation, trenching or work near excavations.','Graving, grøftearbeid eller arbeid nær utgraving.'),hazards:[
    H('collapse','Ground collapse','Ras / sammenrasing',[["Burial, crushing or fatality","Begravning, klemskade eller dødsfall"]],[['support','Assess ground and provide suitable support/slope where needed','Vurder grunnforhold og etabler egnet sikring/skråning ved behov']]),
    H('services','Underground services','Nedgravde installasjoner',[["Electric shock, gas release, flooding or damage","Strømgjennomgang, gasslekkasje, oversvømmelse eller skade"]],[['locate','Locate/identify underground services before excavation','Lokaliser/identifiser nedgravde installasjoner før graving']]),
    H('fall','Fall into excavation','Fall i utgraving',[["Injury from fall","Personskade ved fall"]],[['barrier','Provide barriers/edge protection where required','Etabler sperring/kantsikring der det kreves']])
  ],questions:[Q('services','Are underground services identified?','Er nedgravde installasjoner identifisert?',true),Q('ground','Are ground conditions and collapse risk assessed?','Er grunnforhold og rasfare vurdert?',true),Q('access','Is safe access/egress provided?','Er sikker adkomst/rømningsvei etablert?',true)]},

  {id:'manual',category:'ergonomic',name:B('Manual handling','Manuell håndtering'),description:B('Lifting, carrying, pushing or pulling by hand.','Løfting, bæring, skyving eller trekking for hånd.'),hazards:[
    H('strain','Musculoskeletal strain','Muskel-/skjelettbelastning',[["Acute or cumulative injury","Akutt eller belastningsrelatert skade"]],[['aid','Use mechanical aids or team handling where appropriate','Bruk mekaniske hjelpemidler eller flere personer der det er egnet'],['route','Plan route and handling before lift','Planlegg rute og håndtering før løft']])
  ],questions:[Q('weight','Are load weight/shape and the handling route understood?','Er vekt/form på lasten og transportveien kjent?',true),Q('aid','Are suitable lifting aids or team handling available where needed?','Er egnede løftehjelpemidler eller flere personer tilgjengelig ved behov?',false)]},

  {id:'pressure_wash',category:'equipment',name:B('Pressure washing','Høytrykksspyling'),description:B('Cleaning with high-pressure water/equipment.','Rengjøring med høytrykksvann/-utstyr.'),hazards:[
    H('injection','High-pressure jet / injection injury','Høytrykksstråle / injeksjonsskade',[["Severe tissue injury","Alvorlig vevsskade"]],[['nozzle','Control nozzle and never direct jet at people','Kontroller dysen og rett aldri strålen mot personer'],['condition','Inspect hose, couplings and equipment before use','Kontroller slange, koblinger og utstyr før bruk']]),
    H('slip','Wet/slippery surfaces','Vått/glatt underlag',[["Slip and fall injury","Skli-/fallskade"]],[['drain','Control drainage and keep walking routes safe','Kontroller avrenning og hold gangveier sikre']]),
    H('electric','Water near electrical equipment','Vann nær elektrisk utstyr',[["Electric shock","Strømgjennomgang"]],[['isolate','Protect/isolate electrical hazards before washing','Beskytt/frakoble elektriske farer før spyling']])
  ],questions:[Q('instruction','Has the operator been instructed in safe use of the pressure washer?','Er operatøren instruert i sikker bruk av høytrykksspyleren?',true),Q('area','Is the work area isolated/protected from other people?','Er arbeidsområdet sperret/sikret mot andre personer?',true)]},


  {id:'cleaning_machine',category:'equipment',name:B('Cleaning machines / floor machines','Renholdsmaskiner / gulvmaskiner'),description:B('Use of scrubber dryers, floor polishers, extraction machines and similar powered cleaning equipment.','Bruk av kombimaskin, skure-/bonemaskin, rensemaskin og annet motorisert renholdsutstyr.'),hazards:[
    H('moving','Rotating/moving machine parts','Roterende/bevegelige maskindeler',[["Crushing, entanglement or impact injury","Klem-, innviklings- eller slagskade"]],[['guard','Use guards/safety devices and never bypass protective functions','Bruk vern/sikkerhetsinnretninger og omgå aldri beskyttelsesfunksjoner','manufacturer','Manufacturer instructions','Produsentinstruksjon'],['stop','Stop and isolate the machine before cleaning, adjustment or clearing jams','Stans og frakoble maskinen før rengjøring, justering eller fjerning av blokkering']]),
    H('electric','Electrical supply / battery','Strømforsyning / batteri',[["Electric shock, burns or fire","Strømgjennomgang, brannskade eller brann"]],[['cable','Inspect cables, plugs, charger and battery before use','Kontroller kabel, støpsel, lader og batteri før bruk'],['wet','Keep electrical connections protected from water','Beskytt elektriske koblinger mot vann']]),
    H('slip','Wet floor / machine movement','Vått gulv / maskinbevegelse',[["Slip, fall or collision injury","Skli-, fall- eller kollisjonsskade"]],[['zone','Mark or isolate wet work areas and maintain safe pedestrian routes','Merk eller sperr av våte arbeidsområder og oppretthold sikre ganglinjer']]),
    H('ergonomic','Pushing, pulling and machine handling','Skyving, trekking og håndtering av maskin',[["Musculoskeletal strain","Muskel-/skjelettbelastning"]],[['adjust','Adjust machine and work method to reduce force and awkward posture','Tilpass maskin og arbeidsmetode for å redusere kraftbruk og ugunstige arbeidsstillinger']])
  ],questions:[Q('trained','Has the operator received necessary equipment-specific training?','Har operatøren fått nødvendig utstyrsspesifikk opplæring?',true),Q('inspection','Has the required pre-use check been completed?','Er påkrevd kontroll før bruk gjennomført?',true)]},

  {id:'construction_cleaning',category:'cleaning',name:B('Construction / post-construction cleaning','Byggrenhold / byggvask'),description:B('Cleaning after construction, refurbishment or renovation with dust, debris and changing site conditions.','Renhold etter bygging, oppussing eller rehabilitering med støv, avfall og skiftende forhold på arbeidsplassen.'),hazards:[
    H('dust','Construction dust / fine particles','Byggstøv / fine partikler',[["Respiratory irritation or long-term lung injury","Irritasjon i luftveier eller langvarig lungeskade"]],[['method','Use cleaning methods that minimise airborne dust; use suitable industrial vacuum/filtration where needed','Bruk rengjøringsmetoder som begrenser støvspredning; bruk egnet industristøvsuger/filtrering ved behov'],['quartz','Clarify whether quartz-containing dust may be present before dry cleaning','Avklar om kvartsholdig støv kan forekomme før tørr rengjøring','requirement','Norwegian Labour Inspection Authority – quartz / construction dust','Arbeidstilsynet – kvarts / byggstøv']]),
    H('sharp','Sharp debris, glass, nails or unfinished surfaces','Skarpt avfall, glass, spiker eller uferdige flater',[["Cuts, puncture wounds or eye injury","Kutt-, stikkskade eller øyeskade"]],[['inspect','Inspect the work area and remove/secure sharp debris before cleaning','Kontroller arbeidsområdet og fjern/sikre skarpt avfall før rengjøring'],['ppe','Use suitable gloves, footwear and eye protection where required','Bruk egnede hansker, sko og øyevern der det kreves']]),
    H('site','Openings, uneven floors and ongoing construction activity','Åpninger, ujevne gulv og pågående byggeaktivitet',[["Fall, collision or struck-by injury","Fall-, kollisjons- eller treffskade"]],[['coordinate','Coordinate cleaning with other trades and secure unsafe zones before entry','Koordiner renhold med andre fag og sikre farlige soner før adgang']])
  ],questions:[Q('site','Has the area been released as safe for cleaning?','Er området frigitt som sikkert for renhold?',true),Q('dust','Are the relevant dust/contamination conditions understood before cleaning starts?','Er relevante støv-/forurensningsforhold kjent før renhold starter?',true)]},

  {id:'floor_care',category:'cleaning',name:B('Floor care / stripping, scrubbing and polishing','Gulvpleie / skuring, polish og boning'),description:B('Periodic treatment of hard floors using chemicals, wet methods and powered equipment.','Periodisk behandling av harde gulv med kjemikalier, våte metoder og maskinelt utstyr.'),hazards:[
    H('wet','Very slippery floor during treatment','Svært glatt gulv under behandling',[["Slip and fall injury to workers or others","Skli- og fallskade på arbeidstakere eller andre"]],[['barrier','Close, mark or physically separate the treated area until the floor is safe','Steng, merk eller fysisk skill av behandlet område til gulvet er sikkert']]),
    H('chemical','Floor-care chemicals','Kjemikalier til gulvbehandling',[["Skin/eye injury or respiratory irritation","Hud-/øyeskade eller irritasjon i luftveier"]],[['sds','Follow product instructions and safety data sheet','Følg produktinstruksjon og sikkerhetsdatablad','requirement','Safety data sheet / product instructions','Sikkerhetsdatablad / produktinstruksjon'],['vent','Ensure adequate ventilation for the products and method used','Sørg for tilstrekkelig ventilasjon for produkter og metode']]),
    H('machine','Rotating floor machine / cables','Roterende gulvmaskin / kabler',[["Impact, entanglement, trip or electric shock","Slag-, innviklings-, snuble- eller strømskade"]],[['inspect','Inspect machine, pad/brush and cable before use','Kontroller maskin, pad/børste og kabel før bruk'],['route','Plan cable routing and keep it away from wet areas and walkways','Planlegg kabelføring og hold kabel unna våte områder og ganglinjer']])
  ],questions:[Q('product','Are the correct product, dilution and pad/brush selected for this floor?','Er riktig produkt, dosering og pad/børste valgt for dette gulvet?',true)]},

  {id:'window_facade_cleaning',category:'cleaning',name:B('Window and facade cleaning','Vinduspuss og fasadevask'),description:B('Cleaning glass and facade surfaces from ground level or with separate access equipment.','Rengjøring av glass- og fasadeflater fra bakken eller med separat adkomstutstyr.'),hazards:[
    H('height','Fall risk from access method','Fallrisiko fra valgt adkomstmetode',[["Serious injury or fatality","Alvorlig personskade eller dødsfall"]],[['access','Select a safe access method and add the relevant height-work activity (lift, ladder, scaffold or roof) when applicable','Velg sikker adkomstmetode og legg til relevant høydeaktivitet (lift, stige, stillas eller tak) når det er aktuelt','requirement','Norwegian Labour Inspection Authority – work at height','Arbeidstilsynet – arbeid i høyden']]),
    H('objects','Dropped tools or equipment','Fallende verktøy eller utstyr',[["Injury to people below","Skade på personer under"]],[['secure','Secure tools/equipment and control the area below','Sikre verktøy/utstyr og kontroller området under']]),
    H('glass','Broken glass / sharp edges','Knust glass / skarpe kanter',[["Cuts and lacerations","Kutt- og skjæreskader"]],[['inspect','Inspect damaged glazing and do not clean unsafe glass before it is secured','Kontroller skadet glass og ikke rengjør usikkert glass før det er sikret']]),
    H('public','Public, entrances and traffic around work zone','Publikum, innganger og trafikk rundt arbeidsområdet',[["Collision or struck-by injury","Kollisjons- eller treffskade"]],[['zone','Establish barriers/signage and safe routes around the work zone','Etabler sperring/skilting og sikre ganglinjer rundt arbeidsområdet']])
  ],questions:[Q('access','Is the actual access method selected and separately assessed?','Er faktisk adkomstmetode valgt og særskilt vurdert?',true),Q('weather','Are current weather and surface conditions acceptable for the selected method?','Er dagens vær- og overflateforhold akseptable for valgt metode?',true)]},

  {id:'carpet_upholstery',category:'cleaning',name:B('Carpet and upholstery extraction cleaning','Teppe- og møbelrens'),description:B('Wet/extraction cleaning of carpets, furniture and textile surfaces.','Våt-/ekstraksjonsrens av tepper, møbler og tekstilflater.'),hazards:[
    H('chemical','Cleaning chemicals / spot removers','Rensekjemikalier / flekkfjernere',[["Skin/eye irritation, burns or inhalation exposure","Hud-/øyeirritasjon, etseskade eller innåndingseksponering"]],[['sds','Use products according to label and safety data sheet','Bruk produkter i henhold til etikett og sikkerhetsdatablad','requirement','Safety data sheet / product instructions','Sikkerhetsdatablad / produktinstruksjon']]),
    H('wet','Wet surfaces and hoses/cables','Våte flater og slanger/kabler',[["Slip or trip injury","Skli- eller snubleskade"]],[['route','Control hoses/cables and mark wet areas','Kontroller slanger/kabler og merk våte områder']]),
    H('electric','Electrical extraction equipment in wet work','Elektrisk renseutstyr ved vått arbeid',[["Electric shock","Strømgjennomgang"]],[['inspect','Inspect plugs/cables/equipment and keep electrical connections dry','Kontroller støpsel/kabler/utstyr og hold elektriske koblinger tørre']]),
    H('handling','Moving furniture and equipment','Flytting av møbler og utstyr',[["Musculoskeletal strain or crush injury","Belastnings- eller klemskade"]],[['aid','Use suitable handling aids/team handling where needed','Bruk egnede hjelpemidler/flere personer ved behov']])
  ],questions:[Q('fabric','Are product and material compatibility checked?','Er produkt- og materialkompatibilitet kontrollert?',true),Q('drying','Can the cleaned area remain protected until it is dry and safe?','Kan det rengjorte området holdes sikret til det er tørt og sikkert?',true)]},

  {id:'damage_cleanup',category:'cleaning',name:B('Water / smoke damage cleanup','Skadebegrensning etter vann-/røykskade'),description:B('Cleanup after water leaks, fire/smoke or similar incidents where contamination and building hazards may be uncertain.','Opprydding og rengjøring etter vannlekkasje, brann/røyk eller lignende hendelser der forurensning og bygningsfarer kan være uavklarte.'),hazards:[
    H('contamination','Unknown contamination, soot, mould or wastewater','Ukjent forurensning, sot, mugg eller avløpsvann',[["Respiratory, skin or biological exposure","Eksponering av luftveier, hud eller biologisk materiale"]],[['identify','Clarify contamination before selecting method and PPE','Avklar forurensning før valg av metode og PVU'],['hygiene','Establish hygiene, waste handling and decontamination routines','Etabler rutiner for hygiene, avfallshåndtering og dekontaminering']]),
    H('electric','Water/fire damage to electrical installations','Vann-/brannskade på elektriske installasjoner',[["Electric shock, arc or fire","Strømgjennomgang, lysbue eller brann"]],[['release','Do not enter or start wet cleanup until electrical safety is clarified','Ikke gå inn eller start våtrengjøring før elsikkerheten er avklart','requirement','Applicable electrical safety requirements','Gjeldende elsikkerhetskrav']]),
    H('structure','Damaged ceilings, walls, glass or building materials','Skadde himlinger, vegger, glass eller bygningsmaterialer',[["Falling objects, collapse or cuts","Fallende gjenstander, sammenrasing eller kuttskader"]],[['inspect','Have the area checked and secure unstable/damaged elements before cleaning','Få området kontrollert og sikre ustabile/skadde deler før rengjøring']])
  ],questions:[Q('released','Has the area been formally released as safe to enter and clean?','Er området formelt frigitt som sikkert å gå inn i og rengjøre?',true)]},

  {id:'industrial_cleaning',category:'cleaning',name:B('Industrial / special cleaning','Industri- og spesialrenhold'),description:B('Cleaning in production, plant or technical environments with process equipment and site-specific hazards.','Renhold i produksjons-, industri- eller tekniske miljøer med prosessutstyr og stedsspesifikke farer.'),hazards:[
    H('energy','Moving machinery / hazardous energy','Bevegelige maskiner / farlig energi',[["Crushing, entanglement, burns or fatal injury","Klem-, innviklings-, brann- eller dødelig skade"]],[['isolate','Coordinate shutdown/isolation and verify safe state before cleaning inside hazard zones','Koordiner stans/frakobling og verifiser sikker tilstand før renhold i faresoner','requirement','Arbeidstilsynet – maskiner / sikkert vedlikehold','Arbeidstilsynet – maskiner / sikkert vedlikehold']]),
    H('process','Unknown process residues / substances','Ukjente prosessrester / stoffer',[["Chemical, biological or thermal exposure","Kjemisk, biologisk eller termisk eksponering"]],[['identify','Identify residues and process hazards before selecting cleaning method','Identifiser rester og prosessfarer før valg av rengjøringsmetode']]),
    H('traffic','Mobile equipment and internal traffic','Mobilt utstyr og interntrafikk',[["Collision or crushing injury","Kollisjons- eller klemskade"]],[['separate','Separate cleaning personnel from moving equipment where practicable','Skill renholdspersonell fra bevegelig utstyr der det er praktisk mulig']])
  ],questions:[Q('permit','Are required site permits and coordination arrangements in place?','Er nødvendige arbeidstillatelser og koordineringsordninger på plass?',true)]},

  {id:'alone',category:'organisation',name:B('Working alone','Alenearbeid'),description:B('Work where immediate assistance may not be available.','Arbeid der umiddelbar hjelp kanskje ikke er tilgjengelig.'),hazards:[
    H('delay','Delayed assistance after incident','Forsinket hjelp etter hendelse',[["Consequences may become more severe","Konsekvensene kan bli mer alvorlige"]],[['contact','Establish contact/check-in arrangements','Etabler kontakt-/innsjekkingsrutiner'],['escalation','Define escalation and emergency response','Definer eskalering og beredskap']])
  ],questions:[Q('suitable','Is the task suitable for working alone?','Er oppgaven egnet for alenearbeid?',true),Q('contact','Is reliable communication available?','Er pålitelig kommunikasjon tilgjengelig?',true),Q('response','Can assistance reach the person quickly enough?','Kan hjelp nå personen raskt nok?',true)]}
];

export const documentTemplates=[
  {id:'blank',name:B('Blank SJA','Tom SJA'),description:B('Start without predefined activities and build the SJA from the actual job.','Start uten forhåndsdefinerte aktiviteter og bygg SJA-en fra den faktiske jobben.'),activities:[],reviewed:'2026-09-02'},
  {id:'construction_cleaning',name:B('Construction / post-construction cleaning','Byggrenhold / byggvask'),description:B('For cleaning after construction or renovation: dust, debris, changing site conditions, chemicals and manual handling.','For renhold etter bygging eller rehabilitering: byggstøv, avfall og skiftende byggeplassforhold. Legg til kjemikalier, maskiner, høydearbeid eller manuell håndtering når det faktisk inngår i oppdraget.'),activities:['construction_cleaning'],reviewed:'2026-09-02'},
  {id:'deep_cleaning',name:B('Periodic deep cleaning','Hovedrengjøring'),description:B('For periodic deep cleaning with wet methods, chemicals, manual handling and powered cleaning equipment.','For periodisk hovedrengjøring med våte metoder, kjemikalier, manuell håndtering og motorisert renholdsutstyr.'),activities:['chemicals','cleaning_machine','manual'],reviewed:'2026-09-02'},
  {id:'window_facade',name:B('Window and facade cleaning','Vinduspuss og fasadevask'),description:B('For window/facade work. Add the actual access method separately when lift, ladder, scaffold or roof work is used.','For vindus-/fasadearbeid. Legg til faktisk adkomstmetode og eventuelle kjemikalier separat når dette faktisk inngår i oppdraget.'),activities:['window_facade_cleaning'],reviewed:'2026-09-02'},
  {id:'floor_care',name:B('Floor care and machine cleaning','Gulvpleie og maskinelt renhold'),description:B('For stripping, scrubbing, polishing and other floor treatment using chemicals and powered floor machines.','For skuring, polish, boning og annen gulvbehandling. Aktiviteten dekker de vanlige kjemikalie-, våtgulv- og maskinfarene; legg til ekstra risikofaktorer bare når oppdraget krever det.'),activities:['floor_care'],reviewed:'2026-09-02'},
  {id:'carpet_upholstery',name:B('Carpet and upholstery cleaning','Teppe- og møbelrens'),description:B('For wet/extraction cleaning of carpets, furniture and textile surfaces with chemicals and electrical cleaning equipment.','For våt-/ekstraksjonsrens av tepper, møbler og tekstilflater. Aktiviteten dekker vanlige kjemikalie-, våtroms-, elektriske og håndteringsfarer.'),activities:['carpet_upholstery'],reviewed:'2026-09-02'},
  {id:'industrial_cleaning',name:B('Industrial and special cleaning','Industri- og spesialrenhold'),description:B('For production and technical environments. Covers process hazards, machinery/energy, residues, chemicals and site coordination.','For produksjons- og tekniske miljøer. Dekker prosessfarer, maskiner/energi, rester og koordinering; legg til egne risikofaktorer for kjemikalier, trafikk, høyde eller lukket rom når dette faktisk gjelder.'),activities:['industrial_cleaning'],reviewed:'2026-09-02'},
  {id:'pressure_facade',name:B('Pressure washing / exterior cleaning','Høytrykksspyling / utvendig vask'),description:B('For high-pressure cleaning with jet/injection hazards, wet surfaces, electrical hazards and chemicals where used.','For høytrykksrengjøring med stråle-/injeksjonsfare, våte flater og elektriske farer. Legg til kjemikalier bare når kjemiske produkter faktisk brukes.'),activities:['pressure_wash'],reviewed:'2026-09-02'},
  {id:'damage_cleanup',name:B('Water / smoke damage cleanup','Skadebegrensning etter vann-/røykskade'),description:B('For incident cleanup with potentially unknown contamination, electrical damage, unstable materials and manual handling.','For skadeopprydding med mulig ukjent forurensning, elektriske skader og ustabile materialer. Legg til kjemikalier eller manuell håndtering når det faktisk inngår.'),activities:['damage_cleanup'],reviewed:'2026-09-02'},
  {id:'lift_window',name:B('Exterior work from boom lift','Utvendig arbeid fra bomlift'),description:B('Source-reviewed starting point for MEWP work: planning, machine instructions, ground/stability, weather, electrical hazards and rescue.','Kildekontrollert startpunkt for liftarbeid: planlegging, bruksanvisning, underlag/stabilitet, vær, elektriske farer og redning.'),activities:['boom_lift'],reviewed:'2026-09-02'},
  {id:'roof_work',name:B('Roof / work at height','Tak / arbeid i høyden'),description:B('Source-reviewed starting point for roof work: fall risk, collective protection, fragile surfaces, access and rescue.','Kildekontrollert startpunkt for takarbeid: fallrisiko, kollektiv sikring, svake flater, adkomst og redning.'),activities:['roof'],reviewed:'2026-09-02'},
  {id:'hot_work',name:B('Hot work','Varme arbeider'),description:B('Starting point for fire/explosion, fumes, combustible materials, extinguishing equipment and applicable hot-work safety rules.','Startpunkt for brann/eksplosjon, røyk/gasser, brennbart materiale, slokkeutstyr og gjeldende sikkerhetsregler for varme arbeider.'),activities:['hot_work'],reviewed:'2026-09-02',reviewBy:'2027-01-01'},
  {id:'lift_operation',name:B('Lifting operation','Løfteoperasjon'),description:B('Source-reviewed starting point for lift planning, suitable lifting gear, suspended loads, visibility/signals and weather.','Kildekontrollert startpunkt for løfteplanlegging, egnet løfteredskap, hengende last, sikt/signaler og vær.'),activities:['lifting'],reviewed:'2026-09-02'},
  {id:'excavation',name:B('Excavation','Gravearbeid'),description:B('Source-reviewed starting point for ground conditions, collapse protection, services, training/plan thresholds, access and escape routes.','Kildekontrollert startpunkt for grunnforhold, rassikring, installasjoner, terskler for opplæring/plan, adkomst og rømningsveier.'),activities:['excavation'],reviewed:'2026-09-02'}
];

export function textFor(value,lang){return value?.[lang]??value?.en??String(value??'');}
export function getActivity(id){return activityLibrary.find(a=>a.id===id)||null;}
export function getTemplate(id){return documentTemplates.find(t=>t.id===id)||documentTemplates[0];}

export function taskFromActivity(activityId,lang='en'){
  const a=getActivity(activityId); if(!a) return null;
  const hazards=[],consequences=[],measures=[],references=[];
  a.hazards.forEach(h=>{
    hazards.push(textFor(h.label,lang));
    h.consequences.forEach(c=>{const v=textFor(c,lang);if(!consequences.includes(v))consequences.push(v);});
    h.measures.forEach(m=>{
      const v=textFor(m.label,lang); if(!measures.includes(v)) measures.push(v);
      if(m.sourceType&&m.sourceType!=='recommended'){
        const title=textFor(m.source,lang);
        if(title&&!references.some(r=>r.title===title)) references.push({id:crypto.randomUUID(),type:m.sourceType,title,note:''});
      }
    });
  });
  return {id:crypto.randomUUID(),activity:textFor(a.name,lang),libraryActivityId:a.id,hazards,consequences,measures,responsible:'',riskBefore:{probability:0,consequence:0},riskAfter:{probability:0,consequence:0},references,smartChecks:a.questions.map(q=>({id:q.id,text:textFor(q.text,lang),critical:!!q.critical,answer:'',comment:''})),ruleContext:{},ruleFindings:[]};
}
