const B=(en,no)=>({en,no});
const S={
 height:'https://www.arbeidstilsynet.no/risikofylt-arbeid/arbeid-i-hoyden/',
 lift:'https://www.arbeidstilsynet.no/risikofylt-arbeid/arbeid-i-hoyden/bruk-av-personlofter/',
 ladder:'https://www.arbeidstilsynet.no/risikofylt-arbeid/arbeid-i-hoyden/sikker-bruk-av-stige-ved-arbeid-i-hoyden/',
 scaffold:'https://www.arbeidstilsynet.no/risikofylt-arbeid/arbeid-i-hoyden/montering-og-bruk-av-stillas/',
 roof:'https://www.arbeidstilsynet.no/risikofylt-arbeid/arbeid-i-hoyden/unnga-fall-ved-arbeid-pa-tak/',
 chemicals:'https://www.arbeidstilsynet.no/risikofylt-arbeid/kjemikalier/kartlegging-eksponering-for-kjemikalier/',
 manual:'https://www.arbeidstilsynet.no/arbeidsmiljo/ergonomi/manuelt-arbeid/tungt-arbeid/',
 alone:'https://www.arbeidstilsynet.no/arbeidstid-og-organisering/alenearbeid/',
 lifting:'https://www.arbeidstilsynet.no/regelverk/forskrifter/forskrift-om-utforelse-av-arbeid/',
 hotWork:'https://www.arbeidstilsynet.no/risikofylt-arbeid/kjemikalier/varmt-arbeid/',
 hotWorkInsurance:'https://brannvernforeningen.no/brannvern-ved-utforelse-av-varme-arbeider-2024.pdf',
 electrical:'https://www.dsb.no/elsikkerhet/hms-og-elulykker/veiledning-til-forskrift-om-sikkerhet-ved-arbeid-i-og-drift-av-elektriske-anlegg/',
 traffic:'https://www.vegvesen.no/fag/publikasjoner/handboker/vegnormalene/n301/',
 trafficPermit:'https://www.vegvesen.no/fag/veg-og-gate/arbeidsvarsling/sok-om-a-varsle-og-sikre-arbeid/',
 confined:'https://www.arbeidstilsynet.no/risikofylt-arbeid/arbeid-i-tank/',
 excavation:'https://www.arbeidstilsynet.no/risikofylt-arbeid/gravearbeid/',
 pressure:'https://www.arbeidstilsynet.no/regelverk/forskrifter/forskrift-om-utforelse-av-arbeid/',
 cleaningChem:'https://www.arbeidstilsynet.no/risikofylt-arbeid/kjemikalier/renholdsarbeid-og-kjemisk-pavirkning/',
 sds:'https://www.arbeidstilsynet.no/risikofylt-arbeid/kjemikalier/stoffkartotek/sikkerhetsdatablad/',
 machine:'https://www.arbeidstilsynet.no/risikofylt-arbeid/maskiner/',
 machineUse:'https://www.arbeidstilsynet.no/risikofylt-arbeid/maskiner/kjop-og-bruk-av-maskiner/',
 training:'https://www.arbeidstilsynet.no/arbeidstid-og-organisering/opplaring/',
 quartz:'https://www.arbeidstilsynet.no/risikofylt-arbeid/kjemikalier/kvarts/',
 ergonomics:'https://www.arbeidstilsynet.no/arbeidsmiljo/ergonomi/'
};
const F=(id,type,en,no,opts={})=>({id,type,label:B(en,no),required:true,...opts});
const SOURCE_TITLE_EN={
 'Arbeidstilsynet – bruk av personløfter':'Norwegian Labour Inspection Authority – use of mobile elevating work platforms',
 'Arbeidstilsynet – sikker bruk av stige':'Norwegian Labour Inspection Authority – safe use of ladders',
 'Forskrift om utførelse av arbeid – stiger':'Regulations concerning the performance of work – ladders',
 'Arbeidstilsynet – montering og bruk av stillas':'Norwegian Labour Inspection Authority – assembly and use of scaffolding',
 'Arbeidstilsynet – arbeid på tak':'Norwegian Labour Inspection Authority – roof work',
 'Arbeidstilsynet – arbeid i høyden':'Norwegian Labour Inspection Authority – work at height',
 'Arbeidstilsynet – arbeid i høyden / fallende gjenstander':'Norwegian Labour Inspection Authority – work at height / falling objects',
 'Arbeidstilsynet – tungt arbeid':'Norwegian Labour Inspection Authority – heavy manual work',
 'Arbeidstilsynet – varmt arbeid':'Norwegian Labour Inspection Authority – hot work',
 'Arbeidstilsynet – kartlegging av kjemisk eksponering':'Norwegian Labour Inspection Authority – assessment of chemical exposure',
 'Arbeidstilsynet – sikkerhetsdatablad':'Norwegian Labour Inspection Authority – safety data sheets',
 'Arbeidstilsynet – renholdsarbeid og kjemisk påvirkning':'Norwegian Labour Inspection Authority – cleaning work and chemical exposure',
 'Arbeidstilsynet – maskiner':'Norwegian Labour Inspection Authority – machinery',
 'Arbeidstilsynet – kjøp og bruk av maskiner':'Norwegian Labour Inspection Authority – purchase and use of machinery',
 'Arbeidstilsynet – opplæring i arbeidsutstyr':'Norwegian Labour Inspection Authority – training in work equipment',
 'Arbeidstilsynet – generelle krav til opplæring':'Norwegian Labour Inspection Authority – general training requirements',
 'Arbeidstilsynet – generelle krav til opplæring og sikker utførelse':'Norwegian Labour Inspection Authority – general training and safe-work requirements',
 'Arbeidstilsynet – kvarts':'Norwegian Labour Inspection Authority – respirable crystalline silica',
 'Arbeidstilsynet – ergonomisk arbeidsmiljø':'Norwegian Labour Inspection Authority – ergonomic working environment',
 'Arbeidstilsynet – ergonomisk arbeidsmiljø / gulv og arbeidsområde':'Norwegian Labour Inspection Authority – ergonomics / floors and work area',
 'Arbeidstilsynet – arbeid i eller på tanker':'Norwegian Labour Inspection Authority – work in or on tanks',
 'Arbeidstilsynet – gravearbeid':'Norwegian Labour Inspection Authority – excavation work',
 'Arbeidstilsynet – alenearbeid':'Norwegian Labour Inspection Authority – working alone',
 'DSB – elsikkerhet / FSE':'DSB – electrical safety / FSE',
 'Statens vegvesen N301 / risikovurdering':'Norwegian Public Roads Administration N301 / risk assessment',
 'Statens vegvesen – søk om arbeidsvarsling':'Norwegian Public Roads Administration – roadwork warning application',
 'Forskrift om utførelse av arbeid kapittel 18':'Regulations concerning the performance of work, Chapter 18',
 'Forskrift om utførelse av arbeid kapittel 20':'Regulations concerning the performance of work, Chapter 20',
 'Forskrift om utførelse av arbeid kapittel 21 / Arbeidstilsynet':'Regulations concerning the performance of work, Chapter 21 / Norwegian Labour Inspection Authority',
 'Forskrift om utførelse av arbeid kapittel 23 / Arbeidstilsynet':'Regulations concerning the performance of work, Chapter 23 / Norwegian Labour Inspection Authority',
 'Forskrift om utførelse av arbeid § 18-5':'Regulations concerning the performance of work § 18-5',
 'Forskrift om utførelse av arbeid § 18-6':'Regulations concerning the performance of work § 18-6',
 'Forskrift om utførelse av arbeid § 18-8':'Regulations concerning the performance of work § 18-8',
 'Forskrift om utførelse av arbeid § 20-1':'Regulations concerning the performance of work § 20-1',
 'Forskrift om utførelse av arbeid § 3-1 / Arbeidstilsynet':'Regulations concerning the performance of work § 3-1 / Norwegian Labour Inspection Authority',
 'Sikkerhetsforskrift for utførelse av varme arbeider':'Norwegian hot-work safety rules',
 'Sikkerhetsforskrift for utførelse av varme arbeider punkt 4.1':'Norwegian hot-work safety rules, section 4.1',
 'Sikkerhetsforskrift for utførelse av varme arbeider punkt 4.3':'Norwegian hot-work safety rules, section 4.3',
 'Sikkerhetsforskrift for utførelse av varme arbeider punkt 4.5':'Norwegian hot-work safety rules, section 4.5',
 'Sikkerhetsforskrift for utførelse av varme arbeider punkt 4.6':'Norwegian hot-work safety rules, section 4.6',
 'Vegnormal N301 Arbeid på og ved veg':'Road standard N301 – work on and alongside roads'
};
const sourceTitle=(title)=>title&&typeof title==='object'?title:B(SOURCE_TITLE_EN[title]||title,title);
const R=(id,severity,type,en,no,source,title,when)=>({id,severity,type,text:B(en,no),source,title:sourceTitle(title),when});
const YES=(id,en,no)=>F(id,'boolean',en,no);

export const ruleProfiles={
 boom_lift:{fields:[YES('riskAssessed','Lift use planned and risk assessed','Bruk av lift planlagt og risikovurdert'),F('workingHeight','number','Working height (m)','Arbeidshøyde (m)',{min:0,step:0.1}),YES('outdoor','Work outdoors','Arbeid utendørs'),YES('nearElectrical','Near electrical installations','Nær elektriske installasjoner'),F('anchorPoint','select','Fall protection requirement in platform','Krav til fallsikring i kurv',{options:[['unknown',B('Unknown','Uavklart')],['yes',B('Required','Påkrevd')],['no',B('Not required','Ikke påkrevd')]]}),YES('manualChecked','Original instructions checked','Original bruksanvisning kontrollert'),YES('groundChecked','Ground/load-bearing capacity checked','Underlag/bæreevne kontrollert')],rules:[
  R('lift_plan','critical','requirement','Lift use must be planned and risk assessed before work starts.','Bruk av lift skal planlegges og risikovurderes før arbeidet starter.',S.lift,'Arbeidstilsynet – bruk av personløfter',c=>c.riskAssessed!==true),
  R('lift_manual','critical','manufacturer','The original instructions and machine limits must be checked before use.','Original bruksanvisning og maskinens bruksgrenser må kontrolleres før bruk.',S.lift,'Arbeidstilsynet – bruk av personløfter',c=>c.manualChecked!==true),
  R('lift_ground','critical','requirement','Ground and set-up conditions must be assessed, including stability and load-bearing capacity.','Underlag og oppstillingsforhold må vurderes, inkludert stabilitet og bæreevne.',S.lift,'Arbeidstilsynet – bruk av personløfter',c=>c.groundChecked!==true),
  R('lift_electric','critical','requirement','Electrical hazards and required safe distances must be clarified before work.','Elektriske farer og nødvendige sikkerhetsavstander må avklares før arbeid.',S.lift,'Arbeidstilsynet – bruk av personløfter',c=>c.nearElectrical===true),
  R('lift_anchor','warning','manufacturer','Whether fall protection is required in the platform depends on the machine instructions and the risk assessment; verify this before use.','Om fallsikring skal brukes i kurven avhenger av maskinens bruksanvisning og risikovurderingen; dette må verifiseres før bruk.',S.lift,'Arbeidstilsynet – bruk av personløfter',c=>c.anchorPoint==='unknown'||!c.anchorPoint)
 ]},
 ladder:{fields:[YES('alternativeChecked','Safer work equipment/collective protection considered','Sikrere arbeidsutstyr/kollektiv sikring vurdert'),F('durationMinutes','number','Total task duration (minutes)','Samlet varighet (minutter)',{min:0,step:1}),YES('useAsAccess','Used as access to roof/platform','Brukes som adkomst til tak/avsats'),YES('nearElectrical','Near electrical installations','Nær elektriske installasjoner'),YES('stableSurface','Stable, load-bearing surface and ladder secured','Stabilt/bæredyktig underlag og stigen sikret')],rules:[
  R('ladder_alternative','critical','requirement','A safer work platform or collective protection must be considered before choosing a ladder for work at height.','Sikrere arbeidsutstyr eller kollektiv sikring må vurderes før stige velges til arbeid i høyden.',S.ladder,'Arbeidstilsynet – sikker bruk av stige',c=>c.alternativeChecked!==true),
  R('ladder_30','warning','recommended','Arbeidstilsynet recommends that a ladder is not used when the total task lasts more than about 30 minutes.','Arbeidstilsynet anbefaler at stige ikke brukes når arbeidsoppgaven samlet varer mer enn omtrent 30 minutter.',S.ladder,'Arbeidstilsynet – sikker bruk av stige',c=>Number(c.durationMinutes)>30),
  R('ladder_surface','critical','requirement','The ladder must stand on a stable, load-bearing and firm surface and be secured against slipping or tipping.','Stigen skal stå på stabilt, bæredyktig og fast underlag og sikres mot utglidning og velting.',S.ladder,'Forskrift om utførelse av arbeid – stiger',c=>c.stableSurface!==true),
  R('ladder_access','info','requirement','When used for access, verify the specific requirements for extension above access level and securing.','Ved bruk som adkomst må konkrete krav til høyde over atkomstnivå og sikring verifiseres.',S.ladder,'Arbeidstilsynet – sikker bruk av stige',c=>c.useAsAccess===true),
  R('ladder_electric','critical','requirement','Electrical safety must be clarified before a ladder is positioned near electrical installations.','Elsikkerhet må avklares før stige plasseres nær elektriske installasjoner.',S.ladder,'Arbeidstilsynet – sikker bruk av stige',c=>c.nearElectrical===true)
 ]},
 scaffold:{fields:[F('platformHeight','number','Highest platform height (m)','Høyde til øverste stillasgulv (m)',{min:0,step:0.1}),YES('assemblyOrChange','Assembly, dismantling or modification','Montering, demontering eller endring'),YES('trainingChecked','Required documented training verified','Påkrevd dokumentert opplæring verifisert'),YES('guardrails','Required guardrails/edge protection in place','Påkrevd rekkverk/kantsikring på plass'),YES('approvedTag','Inspection/status information approved','Kontroll-/statusinformasjon godkjent')],rules:[
  R('scaffold_training','critical','requirement','For assembly, dismantling, modification or inspection where training requirements apply, documented training must be verified.','Ved montering, demontering, endring eller kontroll der opplæringskrav gjelder, må dokumentert opplæring verifiseres.',S.scaffold,'Arbeidstilsynet – montering og bruk av stillas',c=>c.assemblyOrChange===true&&c.trainingChecked!==true),
  R('scaffold_guard','critical','requirement','Required guardrails and edge protection must be in place before use.','Påkrevd rekkverk og kantsikring må være på plass før bruk.',S.scaffold,'Arbeidstilsynet – montering og bruk av stillas',c=>c.guardrails!==true),
  R('scaffold_2m','info','definition','A floor height above 2 m triggers specific guardrail and competence provisions; risk assessment can require protection below 2 m as well.','Gulvhøyde over 2 m utløser særskilte bestemmelser om rekkverk og kompetanse; risikovurderingen kan kreve sikring også under 2 m.',S.scaffold,'Arbeidstilsynet – montering og bruk av stillas',c=>Number(c.platformHeight)>2),
  R('scaffold_tag','critical','requirement','Scaffold status/inspection information must show whether it is approved for use.','Stillasets status-/kontrollinformasjon må vise om det er godkjent for bruk.',S.scaffold,'Arbeidstilsynet – montering og bruk av stillas',c=>c.approvedTag!==true)
 ]},
 roof:{fields:[YES('fallPossible','Possible fall to a lower level','Mulig fall til lavere nivå'),YES('fragileSurface','Fragile/uncertain roof surface','Svakt/uavklart takunderlag'),YES('edgeProtection','Collective edge protection in place','Kollektiv kantsikring på plass'),YES('rescuePlanned','Rescue considered where fall-arrest is used','Redning vurdert der fallsikring brukes')],rules:[
  R('roof_height_definition','info','definition','Work at height is governed by fall risk, not by one universal minimum height.','Arbeid i høyden styres av fallrisiko, ikke av én universell minimumshøyde.',S.height,'Arbeidstilsynet – arbeid i høyden',c=>c.fallPossible===true),
  R('roof_collective','critical','requirement','Collective fall protection must be prioritised over personal fall protection where possible.','Kollektiv fallsikring skal prioriteres fremfor personlig fallsikring der det er mulig.',S.height,'Arbeidstilsynet – arbeid i høyden',c=>c.fallPossible===true&&c.edgeProtection!==true),
  R('roof_fragile','critical','requirement','Fragile or uncertain roof surfaces must be identified and controlled before access/work.','Svake eller uavklarte takflater må identifiseres og sikres før adkomst/arbeid.',S.roof,'Arbeidstilsynet – arbeid på tak',c=>c.fragileSurface===true),
  R('roof_rescue','warning','recommended','Where personal fall-arrest is used, rescue after a fall must be practicable and should be planned before work.','Der personlig fallsikring brukes, må redning etter fall være gjennomførbar og bør planlegges før arbeid.',S.height,'Arbeidstilsynet – arbeid i høyden',c=>c.fallPossible===true&&c.edgeProtection!==true&&c.rescuePlanned!==true)
 ]},
 lifting:{fields:[YES('planned','Lift planned, organised and supervised','Løftet planlagt, organisert og overvåket'),YES('gearSuitable','Lifting equipment/accessories suitable and capacity verified','Løfteutstyr/redskap egnet og kapasitet verifisert'),YES('peopleExcluded','People kept out from under suspended load','Personer holdes unna området under hengende last'),YES('operatorCanSee','Operator can see load throughout operation','Operatør kan se lasten gjennom hele operasjonen'),YES('signalPerson','Competent signal person/communication established when needed','Kompetent signalgiver/kommunikasjon etablert ved behov'),YES('outdoor','Outdoor lifting operation','Løfteoperasjon utendørs'),YES('weatherChecked','Weather limits assessed','Værgrenser vurdert'),YES('personLift','Persons will be lifted','Personer skal løftes'),YES('equipmentForPersons','Equipment/platform designed for lifting persons','Utstyr/plattform beregnet for personløft')],rules:[
  R('lifting_plan','critical','requirement','All lifting operations must be thoroughly planned, closely supervised and carried out safely.','Alle løfteoperasjoner skal planlegges grundig, overvåkes nøye og gjennomføres forsvarlig.',S.lifting,'Forskrift om utførelse av arbeid kapittel 18',c=>c.planned!==true),
  R('lifting_gear','critical','requirement','Lifting accessories must be suitable for the load, lifting points, weather and slinging method.','Løfteredskap skal være tilpasset lasten, gripepunktene, værforholdene og metoden for stropping/huking.',S.lifting,'Forskrift om utførelse av arbeid § 18-6',c=>c.gearSuitable!==true),
  R('lifting_suspended','critical','requirement','Measures must prevent workers from being under suspended loads.','Det skal settes i verk tiltak som hindrer at arbeidstakere kommer under hengende last.',S.lifting,'Forskrift om utførelse av arbeid § 18-6',c=>c.peopleExcluded!==true),
  R('lifting_visibility','critical','requirement','If the operator cannot see the load throughout the operation, a competent person must guide the operator and collision risks must be controlled.','Hvis operatøren ikke kan se lasten gjennom hele operasjonen, må en kompetent person rettlede operatøren og kollisjonsfare kontrolleres.',S.lifting,'Forskrift om utførelse av arbeid § 18-5',c=>c.operatorCanSee===false&&c.signalPerson!==true),
  R('lifting_weather','critical','requirement','Outdoor lifting must not continue when weather conditions prevent safe use of the equipment.','Utendørs løft skal ikke fortsette når værforholdene gjør sikker bruk av utstyret umulig.',S.lifting,'Forskrift om utførelse av arbeid § 18-5',c=>c.outdoor===true&&c.weatherChecked!==true),
  R('lifting_person','critical','requirement','Persons shall normally only be lifted with equipment and a platform designed for lifting persons; exceptional person lifting has strict conditions.','Personer skal som hovedregel bare løftes med utstyr og plattform beregnet for personløft; unntaksvise personløft har strenge vilkår.',S.lifting,'Forskrift om utførelse av arbeid § 18-8',c=>c.personLift===true&&c.equipmentForPersons!==true)
 ]},
 hot_work:{fields:[YES('riskAssessed','Fire/explosion and exposure risks assessed','Brann-/eksplosjons- og eksponeringsfare risikovurdert'),F('insuranceRules','select','Do the Norwegian hot-work insurance safety rules apply?','Gjelder forsikringens sikkerhetsforskrift for varme arbeider?',{options:[['unknown',B('Not clarified','Ikke avklart')],['yes',B('Yes','Ja')],['no',B('No','Nei')]]}),YES('hotWorkChecklist','Required hot-work checklist completed before work','Påkrevd sjekkliste for varme arbeider utfylt før arbeid'),YES('certificatesVerified','Required hot-work certificates verified','Påkrevde sertifikater for varme arbeider verifisert'),YES('combustiblesControlled','Combustible materials removed/protected','Brennbart materiale fjernet/beskyttet'),YES('openingsSealed','Openings in floors, walls and ceilings in the risk area sealed/protected','Åpninger i gulv, vegger og tak i risikoområdet tettet/beskyttet'),YES('extinguishingReady','Suitable extinguishing equipment available','Egnet slokkeutstyr tilgjengelig'),YES('fireWatchReady','Named fire watch and post-work monitoring established when required','Navngitt brannvakt og etterkontroll etablert når det kreves'),YES('ventilationAdequate','Ventilation/source extraction adequate','Ventilasjon/kildeavsug tilstrekkelig'),YES('containerWork','Work on tank/drum/container that contained flammable material','Arbeid på tank/fat/beholder som har inneholdt brannfarlig stoff'),YES('containerCleaned','Container cleaned and made safe before hot work','Beholder rengjort og gjort sikker før varmt arbeid'),YES('alarmAffected','Fire alarm/detection will be isolated or affected','Brannalarm/deteksjon kobles ut eller påvirkes'),YES('fireResponsibleApproved','Isolation approved by person responsible for fire safety','Utkobling godkjent av brannvernansvarlig')],rules:[
  R('hot_risk','critical','requirement','Hot work risks, including fire, explosion, fumes, gases and radiation, must be risk assessed and controlled.','Risiko ved varmt arbeid, inkludert brann, eksplosjon, røyk, gasser og stråling, må risikovurderes og kontrolleres.',S.hotWork,'Arbeidstilsynet – varmt arbeid',c=>c.riskAssessed!==true),
  R('hot_combustibles','critical','requirement','The workplace must be cleared of combustible material, or material that cannot be moved must be protected.','Arbeidsplassen må ryddes for brennbart materiale, eller materiale som ikke kan flyttes må beskyttes.',S.hotWork,'Arbeidstilsynet – varmt arbeid',c=>c.combustiblesControlled!==true),
  R('hot_ext','critical','requirement','Suitable fire-extinguishing equipment must be available.','Egnet brannslokkingsutstyr skal være tilgjengelig.',S.hotWork,'Arbeidstilsynet – varmt arbeid',c=>c.extinguishingReady!==true),
  R('hot_vent','critical','requirement','Where hot work produces contamination, suitable ventilation and process-adapted extraction are required.','Der varmt arbeid danner forurensning, kreves egnet ventilasjon og prosesstilpasset avsug.',S.hotWork,'Arbeidstilsynet – varmt arbeid',c=>c.ventilationAdequate!==true),
  R('hot_container','critical','requirement','Containers that have held flammable/burnable liquids can contain explosive vapour and must be cleaned/made safe before hot work.','Beholdere som har inneholdt brannfarlige/brennbare væsker kan inneholde eksplosiv damp og må rengjøres/gjøres sikre før varmt arbeid.',S.hotWork,'Arbeidstilsynet – varmt arbeid',c=>c.containerWork===true&&c.containerCleaned!==true),
  R('hot_alarm','critical','requirement','If fire detection is isolated, this must be approved by the responsible fire-safety person and routines must ensure rapid reactivation.','Hvis branndeteksjon kobles ut, må dette godkjennes av brannvernansvarlig og rutiner må sikre rask reaktivering.',S.hotWork,'Arbeidstilsynet – varmt arbeid',c=>c.alarmAffected===true&&c.fireResponsibleApproved!==true),
  R('hot_insurance_unknown','warning','definition',"Clarify whether the insurer's Norwegian hot-work safety rules apply to this job; the requirements below depend on that scope.",'Avklar om forsikringens norske sikkerhetsforskrift for varme arbeider gjelder for jobben; kravene under avhenger av dette.',S.hotWorkInsurance,'Sikkerhetsforskrift for utførelse av varme arbeider',c=>!c.insuranceRules||c.insuranceRules==='unknown'),
  R('hot_checklist','critical','requirement','Where the hot-work insurance safety rules apply, the required checklist must be completed and signed before work starts.','Der sikkerhetsforskriften for varme arbeider gjelder, skal påkrevd sjekkliste være utfylt og signert før arbeidet starter.',S.hotWorkInsurance,'Sikkerhetsforskrift for utførelse av varme arbeider punkt 4.1',c=>c.insuranceRules==='yes'&&c.hotWorkChecklist!==true),
  R('hot_openings','critical','requirement','Where the hot-work insurance safety rules apply, openings in floors, walls and ceilings in the risk area must be sealed/protected.','Der sikkerhetsforskriften for varme arbeider gjelder, skal åpninger i gulv, vegger og tak i risikoområdet tettes/beskyttes.',S.hotWorkInsurance,'Sikkerhetsforskrift for utførelse av varme arbeider punkt 4.3',c=>c.insuranceRules==='yes'&&c.openingsSealed!==true),
  R('hot_cert','critical','requirement','Where the hot-work insurance safety rules apply, the performer and fire watch must have valid approved hot-work certificates.','Der sikkerhetsforskriften for varme arbeider gjelder, skal utførende og brannvakt ha gyldig godkjent sertifikat for varme arbeider.',S.hotWorkInsurance,'Sikkerhetsforskrift for utførelse av varme arbeider punkt 4.6',c=>c.insuranceRules==='yes'&&c.certificatesVerified!==true),
  R('hot_watch','critical','requirement','Where the hot-work insurance safety rules apply, a named fire watch must monitor the fire risk during work, pauses and the required period afterwards; the current 2024 rule specifies at least one hour after completion.','Der sikkerhetsforskriften for varme arbeider gjelder, skal navngitt brannvakt overvåke brannrisiko under arbeid, pauser og påkrevd tid etterpå; gjeldende 2024-regel angir minst én time etter avsluttet arbeid.',S.hotWorkInsurance,'Sikkerhetsforskrift for utførelse av varme arbeider punkt 4.5',c=>c.insuranceRules==='yes'&&c.fireWatchReady!==true)
 ]},
 chemicals:{fields:[YES('sdsAvailable','Safety data / product information available','Sikkerhetsdatablad / produktinformasjon tilgjengelig'),YES('exposurePossible','Worker exposure possible','Mulig eksponering av arbeidstaker'),YES('substitutionChecked','Safer substitute considered','Mindre farlig alternativ vurdert'),YES('mixingControlled','Products will not be mixed unless explicitly permitted by product instructions','Produkter blandes ikke med mindre dette uttrykkelig er tillatt i produktinstruksjonen'),YES('storageControlled','Storage and access to chemicals are controlled','Oppbevaring og tilgang til kjemikalier er kontrollert')],rules:[
  R('chem_risk','critical','requirement','Chemical risk assessment must consider hazardous properties, supplier information, amount/use, exposure type, level, duration, frequency and routes.','Risikovurdering av kjemikalier skal blant annet vurdere farlige egenskaper, leverandørinformasjon, mengde/bruk og eksponeringstype, nivå, varighet, hyppighet og eksponeringsveier.',S.chemicals,'Forskrift om utførelse av arbeid § 3-1 / Arbeidstilsynet',()=>true),
  R('chem_sds','critical','requirement','Safety data sheets/product instructions for hazardous cleaning chemicals must be available and used before the products are taken into use.','Sikkerhetsdatablad/produktinstruksjon for farlige renholdskjemikalier må være tilgjengelig og brukes før produktene tas i bruk.',S.sds,'Arbeidstilsynet – sikkerhetsdatablad',c=>c.sdsAvailable!==true),
  R('chem_cleaning','info','requirement','Cleaning chemicals must be used according to product instructions and safety information, including ventilation, PPE, handling and first aid.','Renholdskjemikalier skal brukes i tråd med produktinstruksjon og sikkerhetsinformasjon, inkludert ventilasjon, PVU, håndtering og førstehjelp.',S.cleaningChem,'Arbeidstilsynet – renholdsarbeid og kjemisk påvirkning',()=>true),
  R('chem_hierarchy','warning','requirement','Exposure should be removed or reduced using preventive measures; substitution and technical/collective measures should be considered before relying on PPE.','Eksponering skal fjernes eller reduseres med forebyggende tiltak; substitusjon og tekniske/kollektive tiltak skal vurderes før man baserer seg på personlig verneutstyr.',S.cleaningChem,'Arbeidstilsynet – renholdsarbeid og kjemisk påvirkning',c=>c.exposurePossible===true&&c.substitutionChecked!==true),
  R('chem_mix','critical','requirement','Cleaning products must not be mixed unless the product information explicitly allows it; incompatible products can form toxic gases or cause fire.','Renholdsmidler skal ikke blandes med mindre produktinformasjonen uttrykkelig tillater det; uforenlige produkter kan danne giftige gasser eller medføre brann.',S.cleaningChem,'Arbeidstilsynet – renholdsarbeid og kjemisk påvirkning',c=>c.mixingControlled!==true),
  R('chem_store','warning','requirement','Chemical storage must follow product/safety-data instructions and incompatible products must be kept separated where required.','Kjemikalier må oppbevares i tråd med produkt-/sikkerhetsdatainformasjon, og uforenlige produkter må holdes adskilt der det kreves.',S.cleaningChem,'Arbeidstilsynet – renholdsarbeid og kjemisk påvirkning',c=>c.storageControlled!==true)
 ]},
 electrical:{fields:[F('workType','select','Type of activity','Type aktivitet',{options:[['unknown',B('Not clarified','Ikke avklart')],['deenergized',B('Work on de-energized installation','Arbeid på frakoblet anlegg')],['live',B('Live working','Arbeid under spenning')],['near',B('Work near live installation','Arbeid nær spenningssatt anlegg')],['nonelectrical',B('Non-electrical work near installation','Ikke-elektrisk arbeid nær anlegg')]]}),YES('riskAssessed','Required information obtained and risk assessment completed','Nødvendige opplysninger innhentet og risikovurdering gjennomført'),YES('competenceVerified','Competence/qualification requirements verified','Kompetanse-/kvalifikasjonskrav verifisert'),YES('methodSelected','Safe work method selected','Sikker arbeidsmetode valgt'),YES('barriersEstablished','Required safety barriers/measures established','Påkrevde sikkerhetsbarrierer/-tiltak etablert'),YES('isolated','Installation disconnected where de-energized method is used','Anlegg frakoblet der frakoblet arbeidsmetode brukes'),YES('securedAgainstReconnection','Secured against reconnection','Sikret mot innkobling'),YES('absenceVoltageVerified','Absence of voltage verified','Spenningsløs tilstand kontrollert')],rules:[
  R('elec_plan','critical','requirement','Before work starts, necessary information about the installation must be obtained and a risk assessment performed.','Før arbeid starter skal nødvendige opplysninger om anlegget innhentes og risikovurdering gjennomføres.',S.electrical,'FSE § 10 – planlegging av arbeid',c=>c.riskAssessed!==true),
  R('elec_comp','critical','requirement','Relevant competence and qualification requirements for the activity must be verified.','Relevante kompetanse- og kvalifikasjonskrav for aktiviteten må verifiseres.',S.electrical,'FSE / FEK',c=>c.competenceVerified!==true),
  R('elec_method','critical','requirement','The work method, necessary equipment, protective equipment and personnel must be selected based on the risk assessment.','Arbeidsmetode, nødvendig utstyr, verneutstyr og personell skal velges på grunnlag av risikovurderingen.',S.electrical,'FSE § 10',c=>c.methodSelected!==true),
  R('elec_barriers','critical','requirement','Electrical work must be organised with the required safety barriers and measures for the selected work method.','Elektrisk arbeid må organiseres med nødvendige sikkerhetsbarrierer og tiltak for valgt arbeidsmetode.',S.electrical,'FSE – generelle sikkerhetskrav',c=>c.barriersEstablished!==true),
  R('elec_deenergized','critical','requirement','For work on a de-energized installation: disconnect, secure against reconnection and verify absence of voltage before work.','Ved arbeid på frakoblet anlegg: frakoble, sikre mot innkobling og kontrollere at anlegget er spenningsløst før arbeid.',S.electrical,'FSE § 14',c=>c.workType==='deenergized'&&(c.isolated!==true||c.securedAgainstReconnection!==true||c.absenceVoltageVerified!==true)),
  R('elec_unknown','critical','definition','The electrical work/activity type must be clarified because requirements differ for de-energized work, live work and work near live installations.','Type elektrisk arbeid/aktivitet må avklares fordi kravene er forskjellige for frakoblet arbeid, arbeid under spenning og arbeid nær spenningssatt anlegg.',S.electrical,'FSE – arbeidsmetoder',c=>!c.workType||c.workType==='unknown')
 ]},
 traffic:{fields:[F('roadType','select','Traffic environment','Trafikkmiljø',{options:[['unknown',B('Not clarified','Ikke avklart')],['public',B('Public road','Offentlig veg')],['private',B('Private road/site traffic','Privat veg/anleggstrafikk')],['site',B('Closed worksite/internal traffic','Lukket arbeidsområde/interntrafikk')]]}),YES('requiresWarning','Work requires traffic warning or securing','Arbeidet krever varsling eller sikring av trafikk'),YES('permitApproved','Required permit/traffic-management approval obtained','Påkrevd tillatelse/arbeidsvarsling godkjent'),YES('riskMapped','Traffic risks and conflict points mapped','Trafikkrisiko og konfliktpunkter kartlagt'),YES('separation','Workers and traffic physically separated where practicable','Arbeidstakere og trafikk fysisk separert der mulig'),YES('visibility','Visibility/lighting and high-visibility needs assessed','Sikt/belysning og synlighetsbehov vurdert')],rules:[
  R('traffic_risk','critical','requirement','Traffic risks and conflict points must be mapped and controlled before work starts.','Trafikkrisiko og konfliktpunkter må kartlegges og kontrolleres før arbeidet starter.',S.traffic,'Statens vegvesen N301 / risikovurdering',c=>c.riskMapped!==true),
  R('traffic_public','critical','requirement','Work on or by a public road that requires warning or securing requires approval from the responsible road authority.','Arbeid på eller ved offentlig veg som krever varsling eller sikring, krever godkjenning fra ansvarlig vegmyndighet.',S.trafficPermit,'Statens vegvesen – søk om arbeidsvarsling',c=>c.roadType==='public'&&c.requiresWarning===true&&c.permitApproved!==true),
  R('traffic_n301','info','requirement','For public roads, traffic warning and securing must follow applicable road-authority requirements, including N301 where applicable.','På offentlig veg skal varsling og sikring følge gjeldende krav fra vegmyndigheten, inkludert N301 der den gjelder.',S.traffic,'Vegnormal N301 Arbeid på og ved veg',c=>c.roadType==='public'),
  R('traffic_separation','warning','recommended','Separate workers and moving traffic physically where practicable; where not possible, establish equivalent traffic-control measures.','Skill arbeidstakere og bevegelig trafikk fysisk der det er praktisk mulig; der det ikke er mulig, etabler tilsvarende trafikkregulerende tiltak.',S.traffic,'Vegnormal N301 Arbeid på og ved veg',c=>c.separation!==true),
  R('traffic_visibility','critical','requirement','Visibility, lighting and warning/safety equipment must be assessed for the actual traffic environment.','Sikt, belysning og varslings-/sikringsutstyr må vurderes for det aktuelle trafikkmiljøet.',S.traffic,'Vegnormal N301 Arbeid på og ved veg',c=>c.visibility!==true)
 ]},
 confined:{fields:[YES('hazardousAtmospherePossible','Fire-hazardous or health-hazardous atmosphere may be present','Brannfarlig eller helsefarlig atmosfære kan forekomme'),YES('atmosphereMeasured','Necessary atmosphere measurements completed','Nødvendige atmosfæremålinger gjennomført'),YES('continuousMonitoringAssessed','Need for continuous measurements assessed','Behov for kontinuerlige målinger vurdert'),YES('ventilationEstablished','Required ventilation established','Nødvendig ventilasjon etablert'),YES('energyIsolated','Hazardous energy/material inflow isolated','Farlig energi/innstrømming av stoff isolert'),YES('rescuePlan','Rescue/evacuation plan and resources ready','Rednings-/evakueringsplan og ressurser klare'),YES('standbyAssessed','Need for standby/safety watch assessed','Behov for sikkerhetsvakt vurdert')],rules:[
  R('conf_atmosphere','critical','requirement','Necessary checks and measurements must verify that the work atmosphere is safe before entry/work.','Nødvendige kontroller og målinger må verifisere at arbeidsatmosfæren er sikker før inngang/arbeid.',S.confined,'Arbeidstilsynet – arbeid i eller på tanker',c=>c.hazardousAtmospherePossible===true&&c.atmosphereMeasured!==true),
  R('conf_continuous','warning','requirement','The need for repeated or continuous measurements must be assessed because conditions can change during the work.','Behov for gjentatte eller kontinuerlige målinger må vurderes fordi forholdene kan endre seg under arbeidet.',S.confined,'Arbeidstilsynet – arbeid i eller på tanker',c=>c.hazardousAtmospherePossible===true&&c.continuousMonitoringAssessed!==true),
  R('conf_vent','critical','requirement','Ventilation and other measures must be established where necessary to maintain a safe atmosphere.','Ventilasjon og andre tiltak må etableres der det er nødvendig for å opprettholde sikker atmosfære.',S.confined,'Arbeidstilsynet – arbeid i eller på tanker',c=>c.hazardousAtmospherePossible===true&&c.ventilationEstablished!==true),
  R('conf_energy','critical','requirement','Hazardous energy and unintended inflow of substances must be controlled before entry where relevant.','Farlig energi og utilsiktet innstrømming av stoffer må kontrolleres før inngang der det er relevant.',S.confined,'Arbeidstilsynet – arbeid i eller på tanker',c=>c.energyIsolated!==true),
  R('conf_rescue','critical','requirement','Rescue and evacuation must be practicable; plan, communication and necessary resources must be ready before entry.','Redning og evakuering må være gjennomførbar; plan, kommunikasjon og nødvendige ressurser må være klare før inngang.',S.confined,'Arbeidstilsynet – arbeid i eller på tanker',c=>c.rescuePlan!==true),
  R('conf_watch','warning','recommended','Assess whether a standby person/safety watch is necessary based on atmosphere, access and rescue conditions.','Vurder om sikkerhetsvakt er nødvendig ut fra atmosfære, adkomst og redningsforhold.',S.confined,'Arbeidstilsynet – arbeid i eller på tanker',c=>c.standbyAssessed!==true)
 ]},
 excavation:{fields:[F('depth','number','Maximum excavation depth (m)','Maksimal gravedybde (m)',{min:0,step:0.1}),YES('groundMapped','Ground conditions and collapse risks mapped','Grunnforhold og rasfare kartlagt'),YES('servicesLocated','Underground services identified/located','Nedgravde installasjoner identifisert/lokalisert'),YES('excavationPlan','Required excavation plan prepared','Påkrevd graveplan utarbeidet'),YES('trainingVerified','Required excavation training verified','Påkrevd opplæring i gravearbeid verifisert'),YES('supportSafe','Sloping/shoring/support solution assessed and safe','Skråning/avstivning/sikring vurdert og sikker'),YES('spoilDistance','Excavated material kept at least 1 m from edge or otherwise safely managed','Gravemasser minst 1 m fra kant eller håndtert sikkert på annen måte'),YES('safeAccess','Safe access provided','Sikker adkomst etablert'),YES('escapeRoute','Required escape route(s) provided','Påkrevd(e) rømningsvei(er) etablert')],rules:[
  R('exc_ground','critical','requirement','Ground conditions and other risk factors must be mapped and risk assessed before excavation.','Grunnforhold og andre risikoforhold må kartlegges og risikovurderes før graving.',S.excavation,'Arbeidstilsynet – gravearbeid',c=>c.groundMapped!==true),
  R('exc_services','critical','requirement','Underground services and other hazards must be identified before excavation starts.','Nedgravde installasjoner og andre farer må identifiseres før graving starter.',S.excavation,'Arbeidstilsynet – gravearbeid',c=>c.servicesLocated!==true),
  R('exc_125_plan','critical','requirement','For excavation deeper than 1.25 m, a work/excavation plan based on mapping and risk assessment is required.','Ved graving dypere enn 1,25 m kreves plan for arbeidet basert på kartlegging og risikovurdering.',S.excavation,'Forskrift om utførelse av arbeid kapittel 21 / Arbeidstilsynet',c=>Number(c.depth)>1.25&&c.excavationPlan!==true),
  R('exc_125_training','critical','requirement','Workers involved in excavation deeper than 1.25 m require specific training in excavation work, and the training must be documented.','Arbeidstakere som deltar ved graving dypere enn 1,25 m skal ha særskilt opplæring i gravearbeid, og opplæringen skal dokumenteres.',S.excavation,'Arbeidstilsynet – gravearbeid',c=>Number(c.depth)>1.25&&c.trainingVerified!==true),
  R('exc_support','critical','requirement','Collapse protection, sloping or shoring must be dimensioned and suitable for the actual ground and excavation.','Rassikring, skråning eller avstivning må være dimensjonert og egnet for aktuelle grunnforhold og utgraving.',S.excavation,'Arbeidstilsynet – gravearbeid',c=>c.supportSafe!==true),
  R('exc_spoil','critical','requirement','Excavated material should be placed so it cannot collapse into the excavation; Arbeidstilsynet specifies at least 1 m from the edge.','Gravemasser skal plasseres slik at de ikke kan rase ned i utgravingen; Arbeidstilsynet angir minst 1 m fra gravekanten.',S.excavation,'Arbeidstilsynet – gravearbeid',c=>c.spoilDistance!==true),
  R('exc_access','critical','requirement','All excavations must have safe access.','Alle gravegroper skal ha sikker adkomst.',S.excavation,'Arbeidstilsynet – gravearbeid',c=>c.safeAccess!==true),
  R('exc_escape','critical','requirement','Excavations deeper than 1 m must have one or more escape routes.','Gravegroper dypere enn 1 m skal ha én eller flere rømningsveier.',S.excavation,'Arbeidstilsynet – gravearbeid',c=>Number(c.depth)>1&&c.escapeRoute!==true)
 ]},
 manual:{fields:[F('singleLoadKg','number','Heaviest single lift (kg)','Tyngste enkeltløft (kg)',{min:0,step:0.1}),YES('repetitive','Repeated/manual handling over time','Gjentatt/manuell håndtering over tid'),YES('aidAvailable','Suitable lifting/handling aid available','Egnet løfte-/håndteringshjelpemiddel tilgjengelig')],rules:[
  R('manual_total','warning','requirement','Manual handling must be assessed from the total load, posture, object, work environment, frequency and duration.','Manuell håndtering må vurderes ut fra totalbelastning, arbeidsstilling, objekt, arbeidsmiljø, hyppighet og varighet.',S.manual,'Forskrift om utførelse av arbeid kapittel 23 / Arbeidstilsynet',()=>true),
  R('manual_25','warning','recommended','Arbeidstilsynet recommends avoiding single lifts above 25 kg; this is guidance, not a universal legal cut-off.','Arbeidstilsynet anbefaler å unngå enkeltløft over 25 kg; dette er en anbefaling, ikke en universell lovgrense.',S.manual,'Arbeidstilsynet – tungt arbeid',c=>Number(c.singleLoadKg)>25),
  R('manual_aid','warning','recommended','Use suitable handling aids where they can remove or reduce the load.','Bruk egnede hjelpemidler der de kan fjerne eller redusere belastningen.',S.manual,'Arbeidstilsynet – tungt arbeid',c=>c.repetitive===true&&c.aidAvailable!==true)
 ]},
 pressure_wash:{fields:[F('recoilForce','number','Calculated recoil force (N), if known','Beregnet rekylkraft (N), hvis kjent',{min:0,step:1,required:false}),YES('instructionGiven','Worker instructed in safe use','Arbeidstaker instruert i sikker bruk'),YES('mechanicalGuide','Mechanical guiding device used when required','Mekanisk føring brukes når påkrevd'),YES('bodySupport','Hand-held jet device supported against body when required','Håndholdt stråleinnretning støttes mot kroppen når påkrevd'),YES('triggerFree','Trigger/release valve is not tied or blocked','Avtrekker/utløserventil er ikke bundet eller blokkert'),YES('ppeAssessed','PPE and splash/injection protection assessed','PVU og beskyttelse mot sprut/injeksjon vurdert')],rules:[
  R('pressure_instruction','critical','requirement','The employer must instruct workers in safe use of high-pressure washing equipment.','Arbeidsgiver skal instruere arbeidstakerne i sikker bruk av høytrykksspyleutstyr.',S.pressure,'Forskrift om utførelse av arbeid § 20-1',c=>c.instructionGiven!==true),
  R('pressure_250','critical','requirement','A mechanical guiding device is required when calculated recoil force exceeds 250 N.','Anordning for mekanisk føring kreves når beregnet rekylkraft overstiger 250 N.',S.pressure,'Forskrift om utførelse av arbeid § 20-1',c=>Number(c.recoilForce)>250&&c.mechanicalGuide!==true),
  R('pressure_150','critical','requirement','A hand-held jet device must be supported against the body when recoil force exceeds 150 N.','Håndholdt stråleinnretning skal støttes mot kroppen når rekylkraften overstiger 150 N.',S.pressure,'Forskrift om utførelse av arbeid § 20-1',c=>Number(c.recoilForce)>150&&c.bodySupport!==true),
  R('pressure_trigger','critical','requirement','The trigger or release valve must never be tied or otherwise blocked.','Avtrekker eller utløserventil skal aldri bindes opp eller blokkeres.',S.pressure,'Forskrift om utførelse av arbeid § 20-1',c=>c.triggerFree!==true),
  R('pressure_ppe','warning','requirement','Required protective equipment and protection against jet, splash and injection injury must be assessed for the actual operation.','Nødvendig verneutstyr og beskyttelse mot stråle, sprut og injeksjonsskade må vurderes for den aktuelle operasjonen.',S.pressure,'Forskrift om utførelse av arbeid kapittel 20',c=>c.ppeAssessed!==true)
 ]},
 cleaning_machine:{fields:[YES('manualChecked','Manufacturer instructions available and reviewed','Produsentens bruksanvisning tilgjengelig og gjennomgått'),YES('trainingVerified','Necessary equipment-specific/safety training verified','Nødvendig utstyrsspesifikk/sikkerhetsopplæring verifisert'),YES('preUseChecked','Pre-use condition and safety devices checked','Tilstand og sikkerhetsinnretninger kontrollert før bruk'),YES('electricalChecked','Cable, plug, charger/battery and electrical condition checked','Kabel, støpsel, lader/batteri og elektrisk tilstand kontrollert'),YES('areaControlled','Work area and pedestrian interface controlled','Arbeidsområde og kontakt med gående kontrollert')],rules:[
  R('cm_manual','critical','manufacturer','The machine must be used within the manufacturer instructions and intended use.','Maskinen må brukes innenfor produsentens bruksanvisning og tiltenkte bruksområde.',S.machineUse,'Arbeidstilsynet – kjøp og bruk av maskiner',c=>c.manualChecked!==true),
  R('cm_training','critical','requirement','Workers must receive the training and information necessary for safe use of the actual work equipment; documented training is required where the risk assessment indicates particular care is necessary.','Arbeidstakere skal få nødvendig opplæring og informasjon for sikker bruk av det aktuelle arbeidsutstyret; dokumentert opplæring kreves der risikovurderingen viser at særlig forsiktighet er nødvendig.',S.training,'Arbeidstilsynet – opplæring i arbeidsutstyr',c=>c.trainingVerified!==true),
  R('cm_condition','critical','requirement','Safety devices, condition and user checks must be verified before use and defects must not be bypassed.','Sikkerhetsinnretninger, tilstand og brukerkontroller må verifiseres før bruk, og feil skal ikke omgås.',S.machine,'Arbeidstilsynet – maskiner',c=>c.preUseChecked!==true),
  R('cm_electric','critical','manufacturer','Electrical supply, cables, plugs, charging and battery condition must be safe for the actual environment, especially during wet cleaning.','Strømforsyning, kabler, støpsler, lading og batteritilstand må være sikker for det aktuelle miljøet, særlig ved vått renhold.',S.machineUse,'Arbeidstilsynet – kjøp og bruk av maskiner',c=>c.electricalChecked!==true),
  R('cm_area','warning','requirement','The work area must be organised so use of the machine does not expose workers or others to collision, slip or other foreseeable hazards.','Arbeidsområdet må organiseres slik at bruk av maskinen ikke utsetter arbeidstakere eller andre for kollisjon, skliing eller andre forutsigbare farer.',S.machine,'Arbeidstilsynet – maskiner',c=>c.areaControlled!==true)
 ]},
 construction_cleaning:{fields:[YES('dustAssessed','Construction dust and likely contaminants assessed','Byggstøv og sannsynlige forurensninger vurdert'),YES('quartzPossible','Quartz-containing dust may be present','Kvartsholdig støv kan forekomme'),YES('dustMethodSafe','Cleaning method limits airborne dust','Rengjøringsmetoden begrenser støvspredning'),YES('siteReleased','Area coordinated/released as safe for cleaning','Området koordinert/frigitt som sikkert for renhold'),YES('sharpWasteControlled','Sharp/hazardous waste controlled','Skarpt/farlig avfall kontrollert')],rules:[
  R('bc_dust','critical','requirement','Dust exposure must be identified and assessed before selecting the cleaning method and protective measures.','Støveksponering må identifiseres og vurderes før rengjøringsmetode og vernetiltak velges.',S.cleaningChem,'Arbeidstilsynet – renholdsarbeid og kjemisk påvirkning',c=>c.dustAssessed!==true),
  R('bc_quartz','critical','requirement','If quartz-containing dust may be present, quartz exposure must be specifically assessed and controlled; avoid methods that unnecessarily disperse respirable dust.','Hvis kvartsholdig støv kan forekomme, må kvartseksponering vurderes og kontrolleres særskilt; unngå metoder som unødig sprer respirabelt støv.',S.quartz,'Arbeidstilsynet – kvarts',c=>c.quartzPossible===true&&c.dustMethodSafe!==true),
  R('bc_site','critical','requirement','Cleaning must be coordinated with ongoing work so workers are not sent into uncontrolled construction hazards.','Renhold må koordineres med pågående arbeid slik at arbeidstakere ikke sendes inn i ukontrollerte byggeplassfarer.',S.training,'Arbeidstilsynet – generelle krav til opplæring og sikker utførelse',c=>c.siteReleased!==true),
  R('bc_waste','warning','recommended','Sharp debris and hazardous waste should be identified and controlled before cleaning starts.','Skarpt avfall og farlig avfall bør identifiseres og kontrolleres før renhold starter.',S.cleaningChem,'Arbeidstilsynet – renholdsarbeid og kjemisk påvirkning',c=>c.sharpWasteControlled!==true)
 ]},
 floor_care:{fields:[YES('areaClosed','Area can be closed/marked until floor is safe','Området kan stenges/merkes til gulvet er sikkert'),YES('productInfo','Product instructions/SDS reviewed','Produktinstruksjon/SDS gjennomgått'),YES('ventilation','Ventilation suitable for products and method','Ventilasjon egnet for produkter og metode'),YES('machineChecked','Floor machine and pad/brush/cable checked','Gulvmaskin og pad/børste/kabel kontrollert')],rules:[
  R('fc_slip','critical','requirement','Wet or treated floors must be controlled so workers and others are not exposed to avoidable slip hazards.','Våte eller behandlede gulv må kontrolleres slik at arbeidstakere og andre ikke utsettes for unødvendig sklifare.',S.ergonomics,'Arbeidstilsynet – ergonomisk arbeidsmiljø / gulv og arbeidsområde',c=>c.areaClosed!==true),
  R('fc_product','critical','requirement','Product instructions and safety data must be reviewed for floor-care chemicals before use.','Produktinstruksjon og sikkerhetsdatablad må gjennomgås for gulvpleiekjemikalier før bruk.',S.cleaningChem,'Arbeidstilsynet – renholdsarbeid og kjemisk påvirkning',c=>c.productInfo!==true),
  R('fc_vent','warning','requirement','Ventilation and exposure controls must be suitable for the products and application method.','Ventilasjon og eksponeringskontroll må være egnet for produktene og påføringsmetoden.',S.cleaningChem,'Arbeidstilsynet – renholdsarbeid og kjemisk påvirkning',c=>c.ventilation!==true),
  R('fc_machine','critical','requirement','Powered floor equipment must be checked and used safely in accordance with training and manufacturer instructions.','Motorisert gulvutstyr må kontrolleres og brukes sikkert i samsvar med opplæring og produsentinstruksjon.',S.machine,'Arbeidstilsynet – maskiner',c=>c.machineChecked!==true)
 ]},
 window_facade_cleaning:{fields:[F('accessMethod','select','Access method','Adkomstmetode',{options:[['ground',B('Ground / pole system','Bakke / skaftsystem')],['lift',B('Boom lift / MEWP','Bomlift / personløfter')],['ladder',B('Ladder','Stige')],['scaffold',B('Scaffold','Stillas')],['roof',B('Roof / rope / other height access','Tak / tau / annen høydeadkomst')],['unknown',B('Not clarified','Ikke avklart')]]}),YES('areaBelowControlled','Area below/work zone controlled','Området under/arbeidssonen kontrollert'),YES('weatherAssessed','Weather and surface conditions assessed','Vær- og overflateforhold vurdert')],rules:[
  R('wf_access','critical','requirement','The access method must be selected from the actual fall risk and the work must be planned so height work can be performed safely.','Adkomstmetoden må velges ut fra faktisk fallrisiko, og arbeidet må planlegges slik at arbeid i høyden kan utføres sikkert.',S.height,'Arbeidstilsynet – arbeid i høyden',c=>!c.accessMethod||c.accessMethod==='unknown'),
  R('wf_height','info','requirement','When lift, ladder, scaffold, roof or other height access is used, the relevant height-work requirements and activity-specific controls must also be assessed.','Når lift, stige, stillas, tak eller annen høydeadkomst brukes, må relevante krav til arbeid i høyden og aktivitetsspesifikke tiltak også vurderes.',S.height,'Arbeidstilsynet – arbeid i høyden',c=>c.accessMethod&&c.accessMethod!=='ground'&&c.accessMethod!=='unknown'),
  R('wf_below','critical','requirement','People below and around the work must be protected from falling objects, equipment and the work zone.','Personer under og rundt arbeidet må beskyttes mot fallende gjenstander, utstyr og arbeidsområdet.',S.height,'Arbeidstilsynet – arbeid i høyden',c=>c.areaBelowControlled!==true),
  R('wf_weather','warning','requirement','Weather and surface conditions must be considered where they affect safe access, stability or fall risk.','Vær- og overflateforhold må vurderes når de påvirker sikker adkomst, stabilitet eller fallrisiko.',S.height,'Arbeidstilsynet – arbeid i høyden',c=>c.weatherAssessed!==true)
 ]},
 carpet_upholstery:{fields:[YES('productInfo','Product instructions/SDS reviewed','Produktinstruksjon/SDS gjennomgått'),YES('electricalChecked','Electrical extraction equipment checked','Elektrisk renseutstyr kontrollert'),YES('wetAreaControlled','Wet areas, hoses and cables controlled','Våte områder, slanger og kabler kontrollert'),YES('handlingAssessed','Furniture/equipment handling assessed','Håndtering av møbler/utstyr vurdert')],rules:[
  R('cu_product','critical','requirement','Cleaning products must be used according to product instructions and safety information.','Rengjøringsprodukter må brukes i samsvar med produktinstruksjon og sikkerhetsinformasjon.',S.cleaningChem,'Arbeidstilsynet – renholdsarbeid og kjemisk påvirkning',c=>c.productInfo!==true),
  R('cu_electric','critical','manufacturer','Electrical extraction equipment must be checked and suitable for the wet cleaning environment.','Elektrisk renseutstyr må kontrolleres og være egnet for våtrengjøringsmiljøet.',S.machineUse,'Arbeidstilsynet – kjøp og bruk av maskiner',c=>c.electricalChecked!==true),
  R('cu_wet','warning','requirement','Wet surfaces, hoses and cables must be controlled to avoid slip and trip hazards to workers and others.','Våte flater, slanger og kabler må kontrolleres for å unngå skli- og snublefare for arbeidstakere og andre.',S.ergonomics,'Arbeidstilsynet – ergonomisk arbeidsmiljø',c=>c.wetAreaControlled!==true),
  R('cu_handling','warning','requirement','Manual handling of furniture and equipment must be assessed and suitable aids used where they reduce risk.','Manuell håndtering av møbler og utstyr må vurderes, og egnede hjelpemidler brukes der de reduserer risiko.',S.manual,'Arbeidstilsynet – tungt arbeid',c=>c.handlingAssessed!==true)
 ]},
 damage_cleanup:{fields:[YES('areaReleased','Area declared safe to enter','Området erklært sikkert å gå inn i'),YES('contaminationKnown','Contamination type/source clarified','Type/kilde til forurensning avklart'),YES('electricalSafe','Electrical safety clarified','Elsikkerhet avklart'),YES('structureSafe','Damaged building elements assessed/secured','Skadde bygningsdeler vurdert/sikret')],rules:[
  R('dc_entry','critical','requirement','Do not begin cleanup until immediate site hazards and safe access have been clarified.','Ikke start skadeopprydding før umiddelbare farer og sikker adkomst er avklart.',S.training,'Arbeidstilsynet – generelle krav til opplæring og sikker utførelse',c=>c.areaReleased!==true),
  R('dc_contam','critical','requirement','Unknown chemical/biological contamination must be clarified before cleaning method, hygiene measures and PPE are selected.','Ukjent kjemisk/biologisk forurensning må avklares før rengjøringsmetode, hygienetiltak og PVU velges.',S.cleaningChem,'Arbeidstilsynet – renholdsarbeid og kjemisk påvirkning',c=>c.contaminationKnown!==true),
  R('dc_electric','critical','requirement','Electrical safety must be clarified before wet cleanup or work near damaged electrical installations.','Elsikkerhet må avklares før våtrengjøring eller arbeid nær skadde elektriske installasjoner.',S.electrical,'DSB – elsikkerhet / FSE',c=>c.electricalSafe!==true),
  R('dc_structure','critical','requirement','Unstable or damaged building elements must be assessed and secured before personnel work below or next to them.','Ustabile eller skadde bygningsdeler må vurderes og sikres før personell arbeider under eller ved dem.',S.height,'Arbeidstilsynet – arbeid i høyden / fallende gjenstander',c=>c.structureSafe!==true)
 ]},
 industrial_cleaning:{fields:[YES('siteHazardsKnown','Site/process hazards identified','Sted-/prosessfarer identifisert'),YES('energyIsolated','Hazardous energy/process isolated where required','Farlig energi/prosess frakoblet der det kreves'),YES('residuesKnown','Process residues/substances identified','Prosessrester/stoffer identifisert'),YES('coordinationReady','Site coordination/permit arrangements established','Koordinering/arbeidstillatelse etablert')],rules:[
  R('ic_site','critical','requirement','Industrial cleaning must be planned from the actual process, machinery, traffic and site hazards before work starts.','Industrielt renhold må planlegges ut fra faktiske prosess-, maskin-, trafikk- og stedfarer før arbeidet starter.',S.machine,'Arbeidstilsynet – maskiner',c=>c.siteHazardsKnown!==true),
  R('ic_energy','critical','requirement','Hazardous movement or energy must be stopped/isolated and safe state verified before cleaning inside machinery or process hazard zones.','Farlig bevegelse eller energi må stanses/frakobles og sikker tilstand verifiseres før renhold inne i maskiner eller prosessfaresoner.',S.machineUse,'Arbeidstilsynet – kjøp og bruk av maskiner',c=>c.energyIsolated!==true),
  R('ic_residue','critical','requirement','Process residues and substances must be identified so chemical, biological and thermal exposure controls can be selected.','Prosessrester og stoffer må identifiseres slik at tiltak mot kjemisk, biologisk og termisk eksponering kan velges.',S.chemicals,'Arbeidstilsynet – kartlegging av kjemisk eksponering',c=>c.residuesKnown!==true),
  R('ic_coord','warning','requirement','Coordination with the site/process owner and required permit arrangements must be established before cleaning begins.','Koordinering med sted-/prosesseier og nødvendige arbeidstillatelser må være etablert før renhold starter.',S.training,'Arbeidstilsynet – generelle krav til opplæring',c=>c.coordinationReady!==true)
 ]},
 alone:{fields:[YES('communication','Reliable communication available','Pålitelig kommunikasjon tilgjengelig'),YES('rapidAssistance','Assistance can reach worker in time','Hjelp kan nå arbeidstaker i tide'),YES('highRiskTask','Task has elevated acute risk','Oppgaven har forhøyet akutt risiko')],rules:[
  R('alone_assess','critical','requirement','Working alone requires a specific assessment of hazards, likelihood, consequences, communication and access to assistance.','Alenearbeid krever særskilt vurdering av farer, sannsynlighet, konsekvenser, kommunikasjon og tilgang på hjelp.',S.alone,'Arbeidstilsynet – alenearbeid',()=>true),
  R('alone_comms','critical','requirement','Reliable communication/contact arrangements must be assessed and established when needed.','Pålitelig kommunikasjon/kontaktordning må vurderes og etableres ved behov.',S.alone,'Arbeidstilsynet – alenearbeid',c=>c.communication!==true),
  R('alone_response','critical','requirement','If consequences can become serious because assistance is delayed, the work organisation must be changed or compensating measures established.','Hvis konsekvensene kan bli alvorlige fordi hjelp forsinkes, må organiseringen endres eller kompenserende tiltak etableres.',S.alone,'Arbeidstilsynet – alenearbeid',c=>c.highRiskTask===true&&c.rapidAssistance!==true)
 ]}
};
export function textForRule(v,lang){return v?.[lang]??v?.en??String(v??'');}
export function getRuleProfile(activityId){return ruleProfiles[activityId]||null;}
export function evaluateRules(activityId,context={}){const p=getRuleProfile(activityId);if(!p)return[];return p.rules.filter(r=>{try{return r.when(context||{});}catch{return false;}});}
